on:
  push:
    branches: dev

name: ðŸš€ Deploy dev-site on push on the dev branch
jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: ðŸ”¨ pkg installation and build
        run: |
          npm install
          npm run build

      - name: ðŸ“‚ Sync  file to server 1
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          exclude: |
            **/.vscode/**
            **/.git*
            **/.zip*
            **/.rar*
            **/.git*/**
            **/node_modules/**
          # server-dir: ./oda
          # dangerous-clean-slate: true

     